### ISSUE TITLE
Actividad 5 proceso de negocio en bizagi con web-30

### ISSUE THREAD

**Issue by Kevinosorio77** [SistemasTecTlaxiaco/actividad-5-proceso-de-negocio-en-bizagi-con-web-30-equipo-jad#1]
[Practica 5 proceso de negocio en bizagi con web-30.pdf](https://github.com/user-attachments/files/17122252/Practica.5.proceso.de.negocio.en.bizagi.con.web-30.pdf)

**Comment by MarcoRg06** [comment]
De acuerdo con a rubrica han obtenido el 20% ya que cumplen con los requisitos solicitados

**Comment by josealfredo79** [comment]
Bien hecho y revisadol..
